name: "Docker Build & Push"
on:
  workflow_dispatch: {}

jobs:
  build_push:
    name: "Docker Build & Push"
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 1
