name: "Docker Build & Push"
on:
  workflow_dispatch:
    inputs:
      image_tag_version:
        description: "Image tag version"
        required: true

jobs:
  build_push:
    name: "Docker Build & Push"
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG_BASE: ghcr.io/david-lor/mountagne

    steps:
      # Setup
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      # Registry login
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push
      - name: "Compose image tag"
        run: echo "IMAGE_TAG=${{ env.IMAGE_TAG_BASE}}:${{ github.event.inputs.image_tag_version }}" >> $GITHUB_ENV
      - name: "Docker build"
        run: docker build . -t ${{ env.IMAGE_TAG }}
      - name: "Docker push"
        run: docker push ${{ env.IMAGE_TAG }}
